name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run test:unit
      env:
        CI: true
        
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'master' }}
    needs: test
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: install and build
      - run: npm ci
      - run: npm run build
        env:
          CI: true
      - name: Deploy to production
        uses: awb-pw/deploy-to-github-pages-action@master
        env:
          AUTHOR: TKasekamp
          GITHUB_PAGE_NAME: vue-github-search
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          BUILD_PATH: public
          USERNAME: TKasekamp
          EMAIL: toniskasekamp@gmail.com
